lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, list_teman, friend_detail

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^add-friend/$', add_friend, name='add-friend'),
     url(r'^validate-npm/$', validate_npm, name='validate-npm'),
     url(r'delete-friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete-friend'),
     url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
     url(r'^list-teman/$', list_teman, name='list-teman'),
     url(r'friend-detail/$', friend_detail, name='friend-detail'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
import lab2_addon.urls as lab_2_addon
from lab_1.views import index as index_lab1


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace = 'lab-2-addon')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4,namespace='lab-4')),
    url(r'^lab-5/', include(lab_5,namespace='lab-5')),
    url(r'^lab-6/', include(lab_6,namespace='lab-6')),
    url(r'^lab-7/', include(lab_7,namespace='lab-7')),
    url(r'^lab-8/', include(lab_8,namespace='lab-8')),
    url(r'^lab-9/', include(lab_9,namespace='lab-9')),
    url(r'^lab-10/', include(lab_10,namespace='lab-10')),
    url(r'^$', RedirectView.as_view(url='/lab-4/', permanent = 'true'),name='index')
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    alamat = models.TextField(default = "")
    added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada

    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    paginator = Paginator(mahasiswa_list, 10)

    page = request.GET.get('page')
    try:
    	mahasiswa = paginator.page(page)
    except PageNotAnInteger:
    	mahasiswa = paginator.page(1)
    except EmptyPage:
    	mahasiswa = paginator.page(paginator.num_page)

    friend_list = Friend.objects.all()
    response = {"mahasiswa_list": mahasiswa, "friend_list": friend_list}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

def friend_detail(request):
    id_mahasiswa = request.GET.get("id")
    friend = Friend.objects.get(pk=id_mahasiswa)
    response["friend"] = friend
    return render(request, 'lab_7/detail.html', response)

def list_teman(request):
	friend_list = Friend.objects.all()
	response['friend_list'] = friend_list
	data = serializers.serialize('json', friend_list)

	return HttpResponse(data)

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        alamat = request.POST['alamat']
        taken = Friend.objects.filter(npm=npm)
        if(not taken):
        	friend = Friend(friend_name=name, npm=npm, alamat=alamat)
        	friend.save()
        data = model_to_dict(friend)
        return HttpResponse(data)

def delete_friend(request, friend_id):
    Friend.objects.filter(id=friend_id).delete()
    return HttpResponseRedirect('/lab-7/')

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': Friends.objects.filter(npm = npm) #lakukan pengecekan apakah Friend dgn npm tsb sudah ada
    }
    return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $( document ).ready(function () {
            {# lengkapi pemanggilan ajax berikut untuk mengambil daftar teman yang ada di database #}
            $.ajax({
                method: "GET",
                url: "{% url "lab-7:list-teman" %}",
                success: function (friend_list) {
                    var friendlist = JSON.parse(friend_list)
                    if(friendlist.length == 0){
                        $("#friend-list").append("Tidak ada teman")
                    }
                    else{
                        $.each(friendlist, function(index, friend){
                            var buttonDetail = '<span class="btn btn-xs btn-default pull-right" onClick="detailFriend('+friend.pk+')">Detail</span>'
                            var buttonDelete = '<span class="btn btn-xs btn-default pull-right" onClick="deleteFriend('+friend.pk+')">Delete</span>'
                            var isi = '<a class="list-group-item clearfix"'+' id="friend-list-'+friend.pk+'">'+friend.fields.friend_name+"("+friend.fields.npm+")"+buttonDetail+buttonDelete+'</a>'
                            $("#friend-list").append(isi)
                        })
                    }
                },
            });
        });
        deleteFriend = function(id){
            $.ajax({
                method:"GET",
                url: "delete-friend/"+id,
                success: function(){
                    $("#friend-list-"+id).remove()
                }
            })
        }
        detailFriend = function(id){
            window.open("friend-detail/?id="+id)
        }
    </script>
{% endblock %}

lab_7/templates/lab_7/detail.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<a>{{friend.friend_name}}</a>
<a>{{friend.npm}}</a>
<a>{{friend.alamat}}</a>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                                    <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}','{{mahasiswa.alamat_mhs}}')">
                                        Tambah sebagai teman
                                    </span>
                                </span>
                            </a>
                        {% endfor %}
                        <div class="pagination">
                            <span class="step-links">
                                {% if mahasiswa_list.has_previous %}
                                    <a href="?page={{ mahasiswa_list.previous_page_number }}">&laquo;</a>
                                    <a href="?page={{ mahasiswa_list.previous_page_number }}">{{ mahasiswa_list.previous_page_number }}</a>
                                {% endif %}
                            <span class="current">
                                <a>{{ mahasiswa_list.number }}</a>
                            </span>
                                {% if mahasiswa_list.has_next %}
                                    <a href="?page={{ mahasiswa_list.next_page_number }}">{{ mahasiswa_list.next_page_number }}</a>
                                    <a href="?page={{ mahasiswa_list.next_page_number }}">&raquo;</a>
                                {% endif %}
                            </span>
                        </div>
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    var addFriend = function(nama, npm, alamat) {
        $.ajax({
            method: "POST",
            url: "{% url "lab-7:add-friend" %}",
            data: { name: nama, npm: npm, alamat: alamat},
            success : function (friend) {
                var input = JSON.parse(friend)
                var html = '<a class="list-group-item clearfix">' +input["friend_name"]+'('+input["npm"]+')'+'</a>';
                console.log(html)
                $("#friend-list").append(html)

            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    $("#add-friend").on("submit", function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
        addFriend(name, npm)
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}